### ISSUE TITLE
Make freeMemory compatible for mobile.

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [darkowlzz/freeMemory#31]
The menu item of this extension are deprecated in the newest version. This addon become unuseful.

Also, if possible make freeMemory backward compatible by supporting menu item for older Fx for mobile.

**Comment by darkowlzz** [comment]
Thanks for reporting. 

Fixed in https://github.com/darkowlzz/freeMemory/commit/a8e2db9aa68987517bbe89f5794c0ec08b16fb55

**Comment by KrasnayaPloshchad** [comment]
Oh, sorry, I have noticed this extension is not conpatible with Firefox 38.0.5 when I try to install into Fx for mobile.

**Comment by darkowlzz** [comment]
Me too. Maybe AMO is using the cache and we have to wait for the cache to
update.

**Comment by darkowlzz** [comment]
Okay, the issue was with my generated xpi, I forgot to pass mobile build options.
I have submitted another xpi for review.

Thanks again :)

**Comment by KrasnayaPloshchad** [comment]
Well, the “Add to Firefox” button was changed to gray in the mobile page.
![screenshot_2015-06-10-19-20-59](https://cloud.githubusercontent.com/assets/10364351/8081259/f5ffab4a-0fa5-11e5-83ea-36a5d406434a.png)
![screenshot_2015-06-10-19-25-36](https://cloud.githubusercontent.com/assets/10364351/8081429/409763a4-0fa7-11e5-84bd-3f139050f958.png)

**Comment by darkowlzz** [comment]
Should be fixed now. IDK how the supported version number got reset. It's fine now.

**Comment by KrasnayaPloshchad** [comment]
Now this add-on is available at AMO website.
