### ISSUE TITLE
FreeMemory not working on FF40 (beta at the moment) and up

### ISSUE THREAD

**Issue by mzso** [darkowlzz/freeMemory#32]
The button doesn't appear. Addon not usable at all.

**Comment by StinVec** [comment]
I can support this report. With the release of FF40, the extension can no longer function. The icon is completely gone and it cannot be used. I've read that this issue is affecting several add-ons and being sited as being due to Mozilla having removed the old library for loading icons onto the toolbar in Firefox 40.

**Comment by darkowlzz** [comment]
Thanks for reporting. Would fix it soon.

**Comment by KrasnayaPloshchad** [comment]
In Firefox for Android 41, this addon only “Cycle collection” available.

**Comment by darkowlzz** [comment]
A new version which supports new Firefox has been submitted for review to AMO. Here is the new add-on page https://addons.mozilla.org/en-US/firefox/addon/free-memory-20/ 
Thanks all for reporting. :)

**Comment by mzso** [comment]
Cool.

One question though: why make it a different addon and prevent auto updates for those who have it installed?

**Comment by darkowlzz** [comment]
@mzso because there were breaking changes from Firefox 38 and there are Firefox forks who have decided never to merge the new Add-on SDK and UI stuff in them. So the previous add-on is for old firefox and it's forks and the new add-on is for new Firefox.

**Comment by KrasnayaPloshchad** [comment]
> A new version which supports new Firefox has been submitted for review to AMO. Here is the new add-on page https://addons.mozilla.org/en-US/firefox/addon/free-memory-20/
> Thanks all for reporting. :)

This addon is recognized as “Not Available for Android” in my phone.

**Comment by darkowlzz** [comment]
@KrasnayaPloshchad that's right. I felt there was no need of this add-on in Firefox for android. But I might be wrong. Was it useful in android?

**Comment by KrasnayaPloshchad** [comment]
> that's right. I felt there was no need of this add-on in Firefox for android. But I might be wrong. Was it useful in android?

Yes, it is get an easy way to release the RAM space for Firefox for Android. I have found Firefox for Android sometimes can get large RAM usage quickly when browsing the page, if the RAM size of device is small, the app is easy to crash. So I hope this addon shouldn’t died on the mobile device(s).

**Comment by darkowlzz** [comment]
@KrasnayaPloshchad The new add-on sdk (jpm) for mobile seems to be broken at the moment. I'll update the add-on with mobile support once the sdk is fixed. Also, the old free memory add-on for mobile works good. Although there are some broken parts, it works :)
